AWSTemplateFormatVersion: 2010-09-09
Description: This cloudformation template will create ec2
Parameters:
  FriendlyName:
    Description: Friendly Name
    Type: String
  EC2InstanceType:
    Description: Size of EC2 Instances
    Type: String
    Default: t2.medium
    AllowedValues:
      - t2.micro
      - t2.medium
  EC2AMI:
    Description: ec2 instance AMI
    Type: AWS::EC2::Image::Id

Resources: 
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 'demoaws'
      ImageId: !Ref EC2AMI
      InstanceType: !Ref EC2InstanceType
      NetworkInterfaces:
        - GroupSet:
            - !ImportValue 
              'Fn::Sub': "${FriendlyName}-PubSecGroup" 
          AssociatePublicIpAddress: true
          DeviceIndex: '0'
          DeleteOnTermination: true
          SubnetId: !ImportValue
            'Fn::Sub': "${FriendlyName}-PubSubnet"
      UserData:
        Fn::Base64: |
          #!/bin/bash -ex
          sudo yum install wget vim telnet nmap zip unzip -y
          echo "Install Java JDK 11"
          sudo yum remove -y java
          sudo amazon-linux-extras install java-openjdk11 -y
          sudo ln -s /usr/lib/jvm/jre-11-openjdk-11.0.13.0.8-1.amzn2.0.3.x86_64/bin/java /etc/alternatives/java
          echo "Install Maven"
          sudo yum install -y maven
          echo "Install git"
          sudo yum install -y git
          echo "Install Jenkins"
          sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
          sudo yum install -y jenkins
          sudo chkconfig jenkins on
          echo "Start Jenkins services"
          sudo service jenkins start
          sudo mkdir -p /mnt/artefact
          sudo chmod 777 /mnt/artefact
          sudo yum install epel-release -y
          export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which java)))))
          export PATH=$PATH:$JAVA_HOME/bin
          export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
          sudo setenforce 0
          cat /var/lib/jenkins/secrets/initialAdminPassword
      Tags:
        - Key: Name
          Value: Jenkins

  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: 'demoaws'
      ImageId: !Ref EC2AMI
      InstanceType: !Ref EC2InstanceType
      NetworkInterfaces:
        - GroupSet:
            - !ImportValue 
              'Fn::Sub': "${FriendlyName}-PrivSecGroup" 
          DeviceIndex: '0'
          DeleteOnTermination: true
          SubnetId: !ImportValue
            'Fn::Sub': "${FriendlyName}-PrivSubnet"
      UserData: 
        Fn::Base64: |
          #!/bin/bash -ex
          sudo yum install wget vim telnet nmap zip unzip -y
          echo "Install Java JDK 11"
          sudo yum remove -y java
          sudo amazon-linux-extras install java-openjdk11 -y
          sudo ln -s /usr/lib/jvm/jre-11-openjdk-11.0.13.0.8-1.amzn2.0.3.x86_64/bin/java /etc/alternatives/java
          export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which java)))))
          export PATH=$PATH:$JAVA_HOME/bin
          export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar
          sudo mkdir -p /mnt/artefact
          sudo chmod 777 /mnt/artefact
          sudo setenforce 0
      Tags:
        - Key: Name
          Value: appserver